### ISSUE TITLE
Support for other CPU architectures

### ISSUE THREAD

**Issue by Matheus-Garbelini** [fuzzware-fuzzer/hoedur#3]
Hi @SWW13, do you have any recommendations on the necessary patches logic to support other CPU architectures? For example, can the [hoedur qemu patch file](https://github.com/fuzzware-fuzzer/hoedur/blob/main/qemu-sys/patches/hoedur.patch) be directly applicable to interrupt and TCG specific code of other architectures, or we would require a completely set of patches and hoedur code for a different architecture?

I am particularly interested in nanoMIPS and hexagon architectures which is supported in newest versions of QEMU.

**Comment by SWW13** [comment]
Hi @Matheus-Garbelini, the qemu patch tries to be generic but some arch specific things may be needed for interrupt handling. There are also some changes / arch specific implementations required in hoedur.
The hoedur code base is designed to support other architectures and we had a incomplete prototype of a MIPSEL implementation.

Supporting the newest QEMU version may be difficult due to recent code restructuring in newer QEMU versions which largely breaks our patch.

If you interesting in implementing a new arch send me a mail and I can give you a broad roadmap and things to lookout for. I'm a bit short on time, so it can take some days until I get around to write stuff down.

**Comment by Matheus-Garbelini** [comment]
@SWW13 thanks, will reach out to you later next week.
