### ISSUE TITLE
Problem Encountered with register::write

### ISSUE THREAD

**Issue by Shangzewen** [fuzzware-fuzzer/hoedur#8]
Dear @SWW13 
I encountered an register writing issue with register:;write function.
Based on the attached figure, when i am trying to write a custom value like 0x00000001 to register r3 at address 0x0000577c it does not have the expected result, same thing happens when i trying to write at 0x0000577e. However, when i trying to write to r3 at 0x0000577a which is earlier than 0x0000577c, it has the expected effect (certain function was bypassed). It appears like the register::write function does not shows the desired result at certain address, is it because there is certain execution condition need to be met before the register:: write can take effect? 
![Issue_write_register](https://github.com/user-attachments/assets/da39caca-1fc9-48e8-b6fe-2e5b14578dbb)

**Comment by SWW13** [comment]
I would assume this is due to optimizations in QEMUs TCG, where registers are used in multiple instructions and are not written back to the CPU struct between these instructions. I haven't came across such an issue yet, so I don't have any more insights into your specific issue.

If you want to be on the safe side: basic block hooks should never run into this issue, as all register values have to be written back between basic block transitions.

**Comment by Shangzewen** [comment]
Ahhhh, that make sense. Thanks a lot

**Comment by Shangzewen** [comment]
On the other hand, is there a way to config qemu to disable or reduce this QEMU TCG optimizations?

**Comment by SWW13** [comment]
Not that I'm aware of, you can check the QEMU `./configure` script for any related options.

**Comment by Shangzewen** [comment]
yeap sure, Thanks for the fast response.
